pipeline:
  - name: build
    when:
      - event: manual
      - event: cron
      - event: push
        branch: master
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: lualot/Dockerfile
      repo: koonix/lualot
      tags:
        - v1
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
